# Generated by Django 5.2 on 2025-04-08 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('bias', 'Algorithmic Bias'), ('transparency', 'Model Transparency'), ('privacy', 'Data Privacy'), ('governance', 'AI Governance'), ('impact', 'Societal Impact')], max_length=20)),
                ('summary', models.TextField()),
                ('detailed_description', models.TextField()),
                ('key_lessons', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('guide', 'Guide'), ('framework', 'Framework'), ('checklist', 'Checklist'), ('tool', 'Tool'), ('reference', 'Reference')], max_length=20)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('external_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('model_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('clustering', 'Clustering'), ('nlp', 'Natural Language Processing'), ('computer_vision', 'Computer Vision'), ('other', 'Other')], max_length=20)),
                ('dataset_description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bias_analysis', models.JSONField(blank=True, null=True)),
                ('transparency_analysis', models.JSONField(blank=True, null=True)),
                ('fairness_metrics', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
